<?php

namespace Album\Model;

use Doctrine\ORM\EntityRepository;
use Album\Entity\Album;

/**
 * AlbumService
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumService extends EntityRepository
{
    /**
     * 
     * @param \Album\Entity\Album $album
     * @return type
     */
    public function salvarAlbum(Album $album) 
    {
        try {
            $this->_em->persist($album);
            $this->_em->flush();
        } catch (Exception $exc) {
            $this->_em->rollback();
            echo $exc->getTraceAsString();
        }
        return $album->getId();
    }
    
    /**
     * 
     * @param \Album\Entity\Album $album
     * @return boolean
     */
    public function editarAlbum(Album $album)     
    {
        try {
            $this->_em->merge($album);
            $this->_em->flush();
        } catch (Exception $exc) {
            $this->_em->rollback();
            echo $exc->getTraceAsString();
        }
        return true;
    }
    
    /**
     * 
     * @param \Album\Entity\Album $album
     * @return boolean
     */
    public function removerAlbum(Album $album)
    {
        try {
            $this->_em->remove($album);
            $this->_em->flush();
        } catch (Exception $exc) {
            $this->_em->rollback();
            echo $exc->getTraceAsString();
        }
        return true;
    }
}
