<?php

?>

<div class="unit">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><a href="<?php echo $this->url('home');?>">&times;</a></button>
    <h3>Modal header</h3>
  </div>
  <div class="modal-body">
  
	<canvas id="canvas" height="350" width="600"></canvas>


	<script>

		var barChartData = {
			labels : ["January","February","March","April","May","June","July"],
			datasets : [
				{
					fillColor : "rgba(220,220,220,0.5)",
					strokeColor : "rgba(220,220,220,1)",
					data : [65,59,90,81,56,55,40]
				},
				{
					fillColor : "rgba(151,187,205,0.5)",
					strokeColor : "rgba(151,187,205,1)",
					data : [28,48,40,19,96,27,100]
				}
			]
			
		}

	    var myLine = new Chart(document.getElementById("canvas").getContext("2d")).Bar(barChartData);
	
	</script>  
  
  
  </div>
  <div class="modal-footer">
      <a href="<?php echo $this->url('home');?>" class="btn">Fechar</a>
  </div>
</div>