<?php

?>

<div class="unit">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><a href="<?php echo $this->url('home');?>">&times;</a></button>
    <h3>Modal header</h3>
  </div>
  <div class="modal-body">
  
	<canvas id="meuCanvasGraficoIdades" width="700" height="350">[No canvas support]</canvas>


	<script>
            var dadosIdades = [20,22,34,22,18]
            var idadevilourenco = 20;
            var idadembrena = 22;
            var idadefausto = 34;
            var idadegenes = 22;
            var idadeandre = 18;
        </script>	
	
        <script>		
            window.onload = function ()
           {
               var meuGraficoIdades = new RGraph.Bar('meuCanvasGraficoIdades', dadosIdades);
               meuGraficoIdades.Set('chart.background.barcolor1', 'white');
               meuGraficoIdades.Set('chart.background.barcolor2', 'white');
               meuGraficoIdades.Set('chart.title', 'Exemplo Idades com gráficos em HTML5 - www.vilourenco.com.br');
               meuGraficoIdades.Set('chart.title.vpos', 0.6);
               meuGraficoIdades.Set('chart.labels', ['@vilourenco', '@monteirobrena', '@g0nc1n', '@webgenes', '@andredmolin']);
               meuGraficoIdades.Set('chart.tooltips', ['@vilourenco tem ' + idadevilourenco + ' anos', '@monteirobrena tem ' + idadembrena + ' anos', '@g0nc1n tem ' + idadefausto + ' anos', '@webgenes tem ' + idadegenes + ' anos', '@andredmolin tem ' + idadeandre + ' anos']);
               meuGraficoIdades.Set('chart.text.angle', 45);
               meuGraficoIdades.Set('chart.gutter', 35);
               meuGraficoIdades.Set('chart.shadow', true);
               meuGraficoIdades.Set('chart.shadow.blur', 5);
               meuGraficoIdades.Set('chart.shadow.color', '#aaa');
               meuGraficoIdades.Set('chart.shadow.offsety', -3);
               meuGraficoIdades.Set('chart.colors', ['#00CED1']);
               meuGraficoIdades.Set('chart.key.position', 'gutter');
               meuGraficoIdades.Set('chart.text.size', 10);
               meuGraficoIdades.Set('chart.text.font', 'Georgia');
               meuGraficoIdades.Set('chart.text.angle', 0);
               meuGraficoIdades.Set('chart.grouping', 'stacked');
               meuGraficoIdades.Set('chart.strokecolor', 'rgba(0,0,0,0)');
               meuGraficoIdades.Draw();           
           }
       </script>  
  
  </div>
  <div class="modal-footer">
      <a href="<?php echo $this->url('home');?>" class="btn">Fechar</a>
  </div>
</div>