<?php
$title = 'Deletar album';
$this->headTitle($title);
?>

<?php
$url = $this->url('album', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>

<div class="modal" style="background-color: white; margin-top: 10px;">
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><a href="<?php echo $this->url('album');?>">&times;</a></button>
      <h1><small><?php echo $this->escapeHtml($title); ?></small></h1>
  </div>
  <div class="modal-body">
    <form action="<?php echo $url; ?>" method="post">
    <p>Tem certeza que você deseja excluir
        '<?php echo $this->escapeHtml($album['title']); ?>' /
        '<?php echo $this->escapeHtml($album['artist']); ?>'?
    </p>        
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $album['id']; ?>" />
        <button type="submit" name="del" value="Yes" class="btn btn-success">Sim</button>
        <button type="submit" name="del" value="No" class="btn btn-inverse">Não</button>
    </div>
    </form>
  </div>
  <div class="modal-footer">     
    <a href="<?php echo $this->url('album');?>" class="btn">Fechar</a>    
  </div>
</div>