<?php
$title = 'Álbum';
$this->headTitle($title);
?>
<!--div class="unit">
<!--<div class="modal">>
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><a href="<?php echo $this->url('home'); ?>">&times;</a></button>
      <h1><?php echo $this->escapeHtml($title); ?></h1>
         <form class="form-search">
           <label class="control-label">Buscar: </label>
           <input type="text" class="input-medium search-query">
           <button type="submit" class="btn">Search</button>
      </form>      
  </div>
  <div class="modal-body">             
     <table class="table table-hover">
        <thead>
            <tr>
              <th>Códgio</th>
              <th>Título</th>
              <th>Artista</th>
              <th>&nbsp;</th>
            </tr>
        </thead>
        ?php foreach ($albums as $album) : ?>
        <tr>
            <td>?php echo $this->escapeHtml($album->getId());?></td>
            <td>?php echo $this->escapeHtml($album->getTitle());?></td>
            <td>?php echo $this->escapeHtml($album->getArtist());?></td>
            <td>
                <a class="btn btn-link" href="?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $album->getId()));?>"><i class="icon-edit"></i></a>
                <a class="btn btn-link" href="?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $album->getId()));?>"><i class="icon-trash"></i></a>
            </td>
        </tr>
        ?php endforeach; ?>
     </table>
  </div>
  <div class="modal-footer">     
    <a href="?php echo $this->url('home');?>" class="btn">Fechar</a>
    <a href="?php echo $this->url('album', array('action'=>'add'));?>" class="btn btn-primary">Novo Album</a>
  </div>
</div-->
<div class="topo-table">
    <a href="<?php echo $this->url('album', array('action' => 'add')); ?>" class="btn btn-primary" title="Adicionar Album">Novo Album</a>

    <div class="input-append pull-right">
            <div class="btn-group">
                <a href="<?php echo $this->url('album', 
                        array('action' => 'index'));?>" class="btn" title="Listar Módulo">Buscar</a>
                <input class="span2" placeholder="Localizar Album" id="appendedInputButtons" type="text">
                <div class="btn-group">
                    <button class="btn">Filtro</button>
                    <button data-toggle="dropdown" class="btn dropdown-toggle"><span class="caret"></span></button>
                    <ul class="dropdown-menu pull-right" style="min-width: 100px">
                        <li class="active"><a href="#">Código</a></li>
                        <li><a href="#">Título</a></li>
                        <li><a href="#">Artista</a></li>
                    </ul>
                </div>
            </div>
        
        <div class="btn-group">
            <button class="btn">005</button>
            <button data-toggle="dropdown" class="btn dropdown-toggle"><span class="caret"></span></button>
            <ul class="dropdown-menu pull-right" style="min-width: 74px">
                <li class="active"><a href="#">005</a></li>
                <li><a href="#">010</a></li>
                <li><a href="#">025</a></li>
                <li><a href="#">050</a></li>
                <li><a href="#">100</a></li>
            </ul>
        </div>
    </div>
</div>
<br />
<div class="corpo-table">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Código</th>
                <th>Título</th>
                <th>Artista</th>
                <th>Ação</th>  
            </tr>
        </thead>
        <tbody>
            <?php foreach ($albums as $album) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($album->getId()); ?></td>
                    <td><?php echo $this->escapeHtml($album->getTitle()); ?></td>
                    <td><?php echo $this->escapeHtml($album->getArtist()); ?></td>
                    <td>
                        <a class="btn btn-link" href="<?php echo $this->url('album', array('action' => 'add'));
            ?>" title="Adicionar Album"><i class="icon-adjust"></i></a>
                        <a class="btn btn-link" href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->getId()));
            ?>" title="Editar Album"><i class="icon-edit"></i></a>
                        <a class="btn btn-link" href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->getId()));
            ?>" title="Deletar Album"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="pagination">
        <ul>
            <li><a href="#">Anterior</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">Próximo</a></li>
        </ul>
        <div class="modal-footer">
            <a href="<?php echo $this->url('home'); ?>" class="btn" title="Fechar Módulo">Fechar</a>
        </div>
    </div>
</div>