<!--<div class="modal">>
php
$title = 'Álbum';
$this->headTitle($title);
?>
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><a href="<?php echo $this->url('home'); ?>">&times;</a></button>
      <h1>?php echo $this->escapeHtml($title); ?></h1>
         <form class="form-search">
           <label class="control-label">Buscar: </label>
           <input type="text" class="input-medium search-query">
           <button type="submit" class="btn">Search</button>
      </form>      
  </div>
  <div class="modal-body">             
     <table class="table table-hover">
        <thead>
            <tr>
              <th>Códgio</th>
              <th>Título</th>
              <th>Artista</th>
              <th>&nbsp;</th>
            </tr>
        </thead>
        ?php foreach ($albums as $album) : ?>
        <tr>
            <td>?php echo $this->escapeHtml($album->getId());?></td>
            <td>?php echo $this->escapeHtml($album->getTitle());?></td>
            <td>?php echo $this->escapeHtml($album->getArtist());?></td>
            <td>
                <a class="btn btn-link" href="?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $album->getId()));?>"><i class="icon-edit"></i></a>
                <a class="btn btn-link" href="?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $album->getId()));?>"><i class="icon-trash"></i></a>
            </td>
        </tr>
        ?php endforeach; ?>
     </table>
  </div>
  <div class="modal-footer">     
    <a href="?php echo $this->url('home');?>" class="btn">Fechar</a>
    <a href="?php echo $this->url('album', array('action'=>'add'));?>" class="btn btn-primary">Novo Album</a>
  </div>
</div-->
<div class="unit">
    <div class="modal-header" >
        <script>
		jQuery(function($){
			$('select').each(function(i, e){
				if (!($(e).data('convert') == 'no')) {
					$(e).hide().wrap('<div class="btn-group" id="select-group-' + i + '" />');
					var select = $('#select-group-' + i);
					var current = ($(e).val()) ? $(e).val(): '&nbsp;';
					select.html('<input type="hidden" value="' + $(e).val() + '" name="' + $(e).attr('name') + '" id="' + $(e).attr('id') + '" class="' + $(e).attr('class') + '" /><a class="btn" href="javascript:;">' + current + '</a><a class="btn dropdown-toggle" data-toggle="dropdown" href="javascript:;"><span class="caret"></span></a><ul class="dropdown-menu"></ul>');
					$(e).find('option').each(function(o,q) {
						select.find('.dropdown-menu').append('<li><a href="javascript:;" data-value="' + $(q).attr('value') + '">' + $(q).text() + '</a></li>');
						if ($(q).attr('selected')) select.find('.dropdown-menu li:eq(' + o + ')').click();
					});
					select.find('.dropdown-menu a').click(function() {
						select.find('input[type=hidden]').val($(this).data('value')).change();
						select.find('.btn:eq(0)').text($(this).text());
					});
				}
			});
		});
	</script>
        <h1><small>Módulo Album</small></h1>
        <a href="<?php echo $this->url('album', array('action' => 'add')); ?>" class="btn btn-primary" title="Adicionar Album">Novo Album</a>

        <div class="input-append pull-right">
            <div class="btn-group">
                <label class="btn btn-inverse">Filtros:</label>
                <select class="selectpicker" data-style="btn-primary">
                    <option>Artistas</option>
                    <option>Código</option>
                    <option>Título</option>
                </select>
            </div>
            <div class="btn-group">
                <input class="span2" placeholder="Localizar Album" id="appendedInputButtons" type="text">
                <a href="<?php echo $this->url('album', 
                        array('action' => 'index'));?>" class="btn" title="Listar Módulo">Buscar</a>
            </div>
            <div class="btn-group">
                <label class="btn btn-inverse">Limites:</label>
                <select class="selectpicker" >
                    <option>005</option>
                    <option>010</option>
                    <option>025</option>
                    <option>050</option>
                    <option>100</option>
                    <option>Todos</option>
                </select>
            </div>
        </div>
    </div>
    <div class="modal-body">
        <div class="corpo-table">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Título</th>
                        <th>Artista</th>
                        <th>Ação</th>  
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($this->paginator)): ?>
                    <?php foreach ($this->paginator as $album) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($album->getId()); ?></td>
                            <td><?php echo $this->escapeHtml($album->getTitle()); ?></td>
                            <td><?php echo $this->escapeHtml($album->getArtist()); ?></td>
                            <td>
                                <a class="btn btn-link" href="<?php echo $this->url('album', array('action' => 'add'));
                        ?>" title="Adicionar Album"><i class="icon-adjust"></i></a>
                                <a class="btn btn-link" href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->getId()));
                        ?>" title="Editar Album"><i class="icon-edit"></i></a>
                                <a class="btn btn-link" href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->getId()));
                        ?>" title="Deletar Album"><i class="icon-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal-footer">
            <div class="pagination help-block pull-left">
                <?php echo $this->paginationControl($this->paginator, 
                        'Sliding', 'paginator-slide');?>
            </div>
        <div class="pagination help-block pull-right">
            <a href="<?php echo $this->url('home'); ?>" class="btn" title="Fechar Módulo">Fechar</a>
        </div>
    </div>
</div>